In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('neet_data.xlsx')

In [5]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937914880,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816882944,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490114048,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426631936,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113744896,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995387904,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [6]:
df.columns

Index(['created_at', 'retweet_count', 'source', 'user_id', 'user_name',
       'user_description', 'user_follower_count', 'user_friends_count',
       'user_location', 'user_verified', 'user_url', 'tweet',
       'length_of_tweet'],
      dtype='str')

In [7]:
df.shape

(47381, 13)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  str
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  str
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  str
 5   user_description     36510 non-null  str
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  str
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   str
 11  tweet                47381 non-null  str
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), str(7)
memory usage: 4.4 MB

In [9]:
#3
df.sort_values(by="retweet_count",ascending=False)

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
32860,2020-11-08 05:30:01,614304,Twitter for iPhone,1024658968394625024,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,\xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...,62,115,NaN,False,https://t.co/cHZdP4uOdu,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",140
33262,2020-11-07 21:52:54,581097,Twitter for Android,1099388669448867968,Neet\xf0\x9f\x83\x8fPeet,\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...,11,141,NaN,False,NaN,"RT @KamalaHarris: We did it, @JoeBiden. https:...",63
35111,2020-11-06 14:20:33,381458,Twitter Web App,2578241503,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...,Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...,624,527,read carrd before follow!!,False,https://t.co/XgmHbPUgAi,RT @GretaThunberg: So ridiculous. Donald must ...,140
32585,2020-11-08 07:19:02,204348,Twitter for iPhone,1103362192169188992,Parneet kaur,"\xf0\x9f\x96\x95 all negative , all positive v...",587,193,"New Jersey, USA",False,https://t.co/PXgYJf0gIA,RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...,140
38044,2020-11-04 18:19:13,192350,Twitter for iPhone,54249914,Couture_Neet,snapchat . Neetsobeautiful,547,1182,Miii Casaa,False,NaN,"RT @JoeBiden: Keep the faith, guys. We\xe2\x80...",57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47347,2020-10-30 15:48:45,0,WordPress.com,1259781444185944064,Amazon India Offers,Daily Deal Offers. Follow us to get more Savin...,91,236,NaN,False,https://t.co/NxIJNz4jQH,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47348,2020-10-30 15:48:43,0,WordPress.com,376197627,Manish Salunke,Web Developer,474,1363,"Pune, India",False,NaN,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47349,2020-10-30 15:48:42,0,WordPress.com,1260150415146070016,Swati Sharma \xe2\xad\x90\xe2\xad\x90\xe2\xad\...,\xf0\x9f\x87\xae\xf0\x9f\x87\xb3 INDIAN \xf0\x...,238,485,NaN,False,https://t.co/2HgX7svAne,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47351,2020-10-30 15:46:53,0,Twitter Web App,1222115365880073984,Deepanjali,Speak don't shout,92,23,NaN,False,NaN,@saksham65694969 @CACSCMARajat Neet had isolat...,98
47332,2020-10-30 15:53:51,0,Twitter for Android,1146318087475437952,\xe2\x9d\x84\xef\xb8\x8f CEO of kaiba propagan...,\xef\xbe\x9f\xef\xbd\xa1\xef\xbd\xa5*.\xef\xbe...,523,370,\xe2\x98\x85 28 \xe2\x80\xa2 ca \xe2\x86\x92 a...,False,https://t.co/FnPOaifML8,@AlishizueQ LOL what's a NEET??,31

In [10]:
#4
top = df.iloc[0]

In [11]:
print("highest retweet record:")
print(top[["source","retweet_count","user_name","tweet","created_at","user_url"]])

highest retweet record:
source                                         Twitter for Android
retweet_count                                                  141
user_name                                                     Rumi
tweet            RT @Kwa_Mamkhize: I am giving away R5K to 100 ...
created_at                                     2020-10-31 14:10:28
user_url                                                       NaN
Name: 0, dtype: object

In [12]:
top10 = df.head(10)
total_sum = top10["retweet_count"].sum()
print("top 10 retweet sum is",total_sum)

top 10 retweet sum is 866

In [13]:
android = df[df["source"] == "Twitter for android"]
print("total tweets from android:",android.shape[0])
print("total retweet from android:",android["retweet_count"].sum())

total tweets from android: 0
total retweet from android: 0

In [14]:
max_row = df.loc[df["user_id"].idxmax()]
print("username:",max_row["user_name"])
print("location",max_row["user_location"])

username: Neha Kumari
location nan

In [15]:
print(df.columns)

Index(['created_at', 'retweet_count', 'source', 'user_id', 'user_name',
       'user_description', 'user_follower_count', 'user_friends_count',
       'user_location', 'user_verified', 'user_url', 'tweet',
       'length_of_tweet'],
      dtype='str')

In [19]:
df.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937914880,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816882944,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490114048,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [21]:
# df['followers_friend_ratio'] 
df['user_follower_count'] 
df['user_friends_count']

0         180
1        3002
2        1013
3         467
4          24
         ...
47376     513
47377     754
47378       2
47379    1309
47380      45
Name: user_friends_count, Length: 47381, dtype: int64

In [ ]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937914880,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816882944,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490114048,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426631936,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113744896,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995387904,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [ ]:
print(df.isnull().sum())

created_at                 0
retweet_count              0
source                    19
user_id                    0
user_name                  1
user_description       10871
user_follower_count        0
user_friends_count         0
user_location          21134
user_verified              0
user_url               38101
tweet                      0
length_of_tweet            0
dtype: int64

In [ ]:
df['user_description'].fillna('twitter user',inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_11076\252322186.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['user_description'].fillna('twitter user',inplace=True)

0                                             twitter user
1        Proud dad of three & cat, @SussexCCC fan. CEO ...
2        Wisdom is knowing the right path to take, Inte...
3                                             twitter user
4                       it's not my attitude it's my style
                               ...
47376                                       Bhola sa chora
47377    Random person who likes drawing (but not a \nl...
47378                                         twitter user
47379    Finding the enemies of India \xf0\x9f\x87\xae\...
47380    404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...
Name: user_description, Length: 47381, dtype: str

In [ ]:
df.dropna(axis=1, inplace=True)

In [22]:
df.insert(2,'is_allow',True)

In [23]:
df.drop('tweet', axis=1, inplace=True)

In [31]:
df.head()

,created_at,retweet_count,is_allow,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,length_of_tweet
0,2020-10-31 14:10:28,141,True,Twitter for Android,1250294694937914880,Rumi,NaN,14,180,NaN,False,NaN,139
1,2020-10-31 14:10:11,1,True,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,140
2,2020-10-31 14:09:48,141,True,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,139
3,2020-10-31 14:09:41,141,True,Twitter for Android,1085818329816882944,The Rus,NaN,147,467,NaN,False,NaN,139
4,2020-10-31 14:09:22,0,True,Twitter for Android,1227501071490114048,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,140

In [32]:
df['created_at'] 
df['created_at'].astype(str)
df[['year','month','day']] = df['created_at'].str.split('-',expand = True)
print(df[['year','month']])

       year month
0      2020    10
1      2020    10
2      2020    10
3      2020    10
4      2020    10
...     ...   ...
47376  2020    10
47377  2020    10
47378  2020    10
47379  2020    10
47380  2020    10

[47381 rows x 2 columns]